import test from 'node:test';
import assert from 'node:assert/strict';
import { decodePaint } from '../src/paint.js';

const A = [0, 0, 0],
  B = [8, 0, 0],
  C = [0, 8, 0],
  AB = [4, 0, 0],
  BC = [4, 4, 0],
  CA = [0, 4, 0];
// Explicit expected world-space polygons, not generated by childrenOf().
const cases = [
  [
    'one split, side 0',
    '481',
    [
      [A, B, BC],
      [BC, C, A],
    ],
  ],
  [
    'one split, side 1',
    '485',
    [
      [B, C, CA],
      [CA, A, B],
    ],
  ],
  [
    'one split, side 2',
    '489',
    [
      [C, A, AB],
      [AB, B, C],
    ],
  ],
  [
    'two splits, side 0',
    '480C2',
    [
      [A, AB, CA],
      [AB, B, CA],
      [B, C, CA],
    ],
  ],
  [
    'two splits, side 1',
    '480C6',
    [
      [B, BC, AB],
      [BC, C, AB],
      [C, A, AB],
    ],
  ],
  [
    'two splits, side 2',
    '480CA',
    [
      [C, CA, BC],
      [CA, A, BC],
      [A, B, BC],
    ],
  ],
  [
    'three splits',
    '480C1C3',
    [
      [A, AB, CA],
      [AB, B, BC],
      [BC, C, CA],
      [AB, BC, CA],
    ],
  ],
];
for (const [name, hex, polygons] of cases)
  test(`paint child position and material: ${name}`, () => {
    const result = decodePaint([A, B, C], hex).sort((a, b) => a.material - b.material);
    assert.deepEqual(
      result,
      polygons.map((v, i) => ({ v, material: i + 1 })),
    );
  });
test('nested mixed splits keep child labels in their spatial regions', () => {
  // Root: one split (side 0). Child 0: two splits (side 1).
  // Child 1: uniform slot 4. Literal leaves have distinct, checkable positions.
  const result = decodePaint([A, B, C], '480C61C1').sort((a, b) => a.material - b.material);
  assert.deepEqual(result, [
    { material: 1, v: [B, [6, 2, 0], AB] },
    { material: 2, v: [[6, 2, 0], BC, AB] },
    { material: 3, v: [BC, A, AB] },
    { material: 4, v: [BC, C, A] },
  ]);
});
test('unpainted leaves use the assigned volume material without recoloring neighbors', () => {
  const result = decodePaint([A, B, C], '041', 7).sort((a, b) => a.material - b.material);
  assert.deepEqual(result, [
    { v: [BC, C, A], material: 1 },
    { v: [A, B, BC], material: 7 },
  ]);
});
for (const dialect of ['prusa', 'bambu'])
  test(`${dialect} rejects truncated extended states and excessive nesting`, () => {
    assert.throws(
      () => decodePaint([A, B, C], dialect === 'prusa' ? 'EC' : 'FC', 1, dialect),
      /Truncated/,
    );
    assert.throws(() => decodePaint([A, B, C], '1'.repeat(42), 1, dialect), /deeply/);
  });
